### ISSUE TITLE
CMake for running pulse regression test

### ISSUE THREAD

**Issue by rupertnash** [otbrown/LAMBReX#1] opened 2019-02-22 16:58 UTC
I'm not happy about make running the pulse example! This won't work in a cross-compiling env (eg ARCHER).

Have a think about the best way to do this.

```cmake
add_custom_command(
  TARGET pulse
  POST_BUILD
  COMMAND ${CMAKE_COMMAND} -E echo "Running $<TARGET_FILE_NAME:pulse> ..."
  COMMAND pulse > pulse.out
  )

add_test(
  NAME "pulse_diff"
  COMMAND ${CMAKE_COMMAND} -E compare_files pulse.out blessed_pulse.out
  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/bins
)
```

**Comment by otbrown** [comment] 2019-02-22 17:12
I hate it too! This was just the first thing I could actually get to work -- very open to finding a better approach.

**Comment by otbrown** [comment] 2019-02-26 11:55
[catch2RegressionTests](https://github.com/otbrown/LAMBReX/blob/master/tests/catch2RegressionTests.cpp) now implements a much more substantial regression test, which checks the entire density array at 3 timesteps (t=0,100,200) in our example calculation. [pulseRegression.h](https://github.com/otbrown/LAMBReX/blob/master/tests/pulseRegression.h) contains the output from prior version of the code.

Since the new regression test is much stricter, I consider the file diff obsolete and will close this issue.

**Closed as completed by otbrown** 2019-02-26 11:55 UTC
Labels: enhancement
